---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: concourse-web-petclinic
  namespace: concourse-petclinic
  labels:
    app: concourse-web
    chart: concourse-14.2.0
    heritage: Helm
    release: concourse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: concourse-web
subjects:
- kind: ServiceAccount
  name: concourse-web
  namespace: delivery
