
#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: concourse-main
type: Opaque
data:
  harborDomain: #@ base64.encode(data.values.commonSecrets.harborDomain)
  harborUser: #@ base64.encode(data.values.commonSecrets.harborUser)
  harborPassword: #@ base64.encode(data.values.commonSecrets.harborPassword)
  tbsProject: #@ base64.encode(data.values.commonSecrets.tbsProject)
  kubeconfigBuildServer: #@ base64.encode(data.values.commonSecrets.kubeconfigBuildServer)
  kubeconfigAppServer: #@ base64.encode(data.values.commonSecrets.kubeconfigAppServer)
  concourseHelperImage: #@ base64.encode(data.values.commonSecrets.concourseHelperImage)
---  
apiVersion: v1
kind: Secret
metadata:
  name: petclinic
  namespace: concourse-main
type: Opaque
data:
  host: #@ base64.encode(data.values.petclinic.host)
  image: #@ base64.encode(data.values.petclinic.image)
  wavefrontApplicationName: #@ base64.encode(data.values.petclinic.applicationName)
  wavefrontUri: #@ base64.encode(data.values.petclinic.wavefront.uri)
  wavefrontApiToken: #@ base64.encode(data.values.petclinic.wavefront.apiToken)
  wavefrontDeployEventName: #@ base64.encode(data.values.petclinic.deployEventName)
  configRepo: #@ base64.encode(data.values.petclinic.configRepo)
  codeRepo: #@ base64.encode(data.values.petclinic.codeRepo)
