
#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: concourse-main
type: Opaque
data:
  harborDomain: #@ base64.encode(data.values.commonSecrets.harborDomain)
  harborUser: #@ base64.encode(data.values.commonSecrets.harborUser)
  harborPassword: #@ base64.encode(data.values.commonSecrets.harborPassword)
  harborProject: #@ base64.encode(data.values.commonSecrets.harborProject)
  tbsProject: #@ base64.encode(data.values.commonSecrets.tbsProject)
  kubeconfigBuildServer: #@ base64.encode(data.values.commonSecrets.kubeconfigBuildServer)
  kubeconfigAppServer: #@ base64.encode(data.values.commonSecrets.kubeconfigAppServer)
---  
apiVersion: v1
kind: Secret
metadata:
  name: petclinic
  namespace: concourse-main
type: Opaque
data:
  host: #@ base64.encode(data.values.petclinicSecrets.host)
  image: #@ base64.encode(data.values.petclinicSecrets.image)
  wavefrontApplicationName: #@ base64.encode(data.values.petclinicSecrets.wavefrontApplicationName)
  wavefrontUri: #@ base64.encode(data.values.petclinicSecrets.wavefrontUri)
  wavefrontApiToken: #@ base64.encode(data.values.petclinicSecrets.wavefrontApiToken)
  configRepo: #@ base64.encode(data.values.petclinicSecrets.configRepo)
  codeRepo: #@ base64.encode(data.values.petclinicSecrets.codeRepo)
